### ISSUE TITLE
nsp check is complaining against accepts@1.2.13

### ISSUE THREAD

**Issue by guerilla7** [heroku/einstein-vision-node#2]
I know its just a demo app but any reason its still using accepts@1.2.13 version?

This version is using negotiator@0.5.3 which is prone to RegEx DoS
https://nodesecurity.io/advisories/106

![screen shot 2017-03-07 at 2 41 41 pm](https://cloud.githubusercontent.com/assets/2307524/23681550/3806ce68-0344-11e7-8022-590e20748dfe.png)

Thanks!
Ron

**Comment by mars** [comment]
Upgraded Express to update those dependencies:

```
└─┬ express@4.15.2 
  ├─┬ accepts@1.3.3 
  │ └── negotiator@0.6.1 
```

**Comment by guerilla7** [comment]
Thanks @mars !
