### ISSUE TITLE
Custom modelId causing internal server error

### ISSUE THREAD

**Issue by Chris-Perkins** [heroku/einstein-vision-node#5]
I am able to run the default master branch heroku setup using "Deploy to Heroku", but whenever I attempt to query an image with a custom modelId I receive an internal error

![screen shot 2017-05-12 at 4 41 48 pm](https://cloud.githubusercontent.com/assets/15268274/26016170/f4b0aaf4-3731-11e7-984a-44bb4b292594.png)

This error does not occur when using the GeneralImageClassifier (default value for modelId)
I have tried setting my custom model using both CLI and Heroku's web interface.

I verified that this error does not occur when querying via curl on the same modelId.

**Comment by mars** [comment]
What's logged for those errors?

```bash
heroku logs -n 1500 -t
```

**Comment by Chris-Perkins** [comment]
Logs posted at https://pastebin.com/hUjwteVi

**Comment by mars** [comment]
So it looks like the file upload is failing with a 403 Access Forbidden error.

~Is the Cloudinary Add-on attached? (Check with `heroku addons`)~

Would you give me some backstory about how you got to this point? The problem is not evident, yet.

**Comment by mars** [comment]
Oh I forgot that everything happens on that `/file-upload` endpoint.

When you say you set a custom model ID, is it one that you trained within the same Add-on / Einstein Vision account?

**Comment by mars** [comment]
https://github.com/heroku/einstein-vision-node#share-a-custom-model

**Comment by Chris-Perkins** [comment]
You are correct; the modelId I use is the one that I received after training the model.

After following the steps in share-a-custom-model, the following was logged to the console:
  Desktop (master) x ?  heroku addons:attach einstein-vision --app [APP NAME]
 ▸    Ambiguous identifier; multiple matching add-ons found:
 ▸    einstein-vision-metric-71881, einstein-vision-spherical-65136.
➜  Desktop (master) x ?  heroku config:set CUSTOM_MODEL_ID=[CUSTOM MODEL ID] --app [APP NAME]
Setting CUSTOM_MODEL_ID and restarting ⬢ [APP NAME]... done, v8
CUSTOM_MODEL_ID: [CUSTOM MODEL ID]
➜  Desktop (master) x ?  heroku open --app [APP NAME]

I'm not quite sure what's going on; I used the "Deploy to heroku" button, and only edited the custom model id without touching any code.

I'm using a Mac if it matters.

**Comment by mars** [comment]
When attaching an add-on, the add-on ID must be specified, like:

```bash
heroku addons:attach einstein-vision-metric-71881 --app [APP NAME]
````

If the target app already has an **einstein-vision** add-on, then that unused add-on should be destroyed before attaching one from another app. Otherwise, the app will have two **einstein-vision** addons. This app will only use one of them, unless you customize the source code to use both.

**Comment by Chris-Perkins** [comment]
Sorry for the late response.

I only attempt to attach the addon after first testing. This isn't really my point, though.

Here are my steps:
1.  Press "Deploy to Heroku" on the readme
2.  [Give it a name](http://i.imgur.com/WR0gZcp.png)
3. [Give it a custom model id](http://i.imgur.com/hBdflCu.png)
4. Press Deploy
5. Launch it using "heroku open..."
6. Attempt to upload an image
7. Get "Internal Server Error"

I have tried setting it back to GeneralImageClassifier. When set to this model, it analyzes the image successfully. I have confirmed my Einstein Vision API credentials are set correctly.

I then attempted removing the Einstein Vision addon and re-adding it using the command you mentioned above, and I get the same error.

What am I missing in this picture? I'm imagining it's something simple, but I can't seem to determine it.

**Comment by mars** [comment]
Are you using credentials (the config vars) from the Einstein Vision Addon to create & train that custom model?

In other words, are you training the custom model with the same Addon (Einstein Vision account) as you are trying to use it?

Every Einstein Vision Addon contains its own account. So the only way to share a custom model is to attach the Addon it was created with to other apps.

**Comment by Chris-Perkins** [comment]
Yes; the credentials are of the same account.

**Comment by mars** [comment]
There is no way the steps you outlined will work with a custom model immediately after "Deploy to Heroku" button, because that new app has a new Einstein Vision Addon without access to the custom model you set.

Immediately remove the EV Addon from the new app. Then addons:attach the EV Addon where the model was created.

Sorry if it sounds like I'm repeating myself, but that's the only solution.

**Comment by mars** [comment]
BTW what do you mean about "setting your Einstein Credentials"?

The addon takes care of that. This app is not setup to let you manually set account login.

**Comment by Chris-Perkins** [comment]
I did not say I set my credentials; I simply confirmed they were correct with `heroku config --app $APP-NAME` since it was suggested that perhaps they were not of the same account.

I have attempted removing the EV addon and re-adding it multiple times, whether through the one-click install at https://elements.heroku.com/addons/einstein-vision or via CLI.

One thing that could be stopping it: You put in an above command "einstein-vision-metric-71881"
Where did you get this specific addon id? Perhaps this is what I'm doing wrong.

**Comment by mars** [comment]
Yes, that addon ID is crucial.

You can see the addon IDs for an app:

```bash
heroku addons --app $APP_NAME
```

When attaching the addon that contains your custom model to another app, its addon ID must be specified.

**Comment by Chris-Perkins** [comment]
I understand this; where do I get my specific addon id for the custom model if it was not yet added? 
If it matters, I should mention again that I tried one-click installing my Einstein Vision model, yet the problem persists.

**Comment by mars** [comment]
How did you create the custom model? What Einstein Vision account did you create it in?
