### ISSUE TITLE
Please support new vision features

### ISSUE THREAD

**Issue by mgcdanny** [heroku/einstein-vision-node#6]
Einstein Vision now has multiple object detection as GA.  Can this app support the "box" drawing from the prediction response? 

Einstein Vision Object Detection
https://metamind.readme.io/docs/od_qs_classify_an_image

Proposed solution.  Use html canvas element overlaid on top of uploaded image:
https://stackoverflow.com/questions/14824747/overlay-html5-canvas-over-image

**Comment by mars** [comment]
Thanks for the suggestion! We're looking into this soon.

**Comment by mars** [comment]
Salesforce is retiring the Object Detection and Image Classification APIs on July 31, 2023
